// Auto-generated by update_manifest.sh — do not edit manually
var CUSTOM_GENOMES = {
  "canola_GCF_020379485.1": {
    "label": "canola_GCF_020379485.1",
    "fasta": "references/canola_GCF_020379485.1/GCF_020379485.1_Da-Ae_genomic.fa",
    "index": "references/canola_GCF_020379485.1/GCF_020379485.1_Da-Ae_genomic.fa.fai",
    "annotation": "references/canola_GCF_020379485.1/GCF_020379485.1_Da-Ae_genomic.gtf",
    "annotationFormat": "gtf"
  },
  "tomato_SLM_r2.1": {
    "label": "tomato_SLM_r2.1",
    "fasta": "references/tomato_SLM_r2.1/SLM_r2.1.fa",
    "index": "references/tomato_SLM_r2.1/SLM_r2.1.fa.fai",
    "annotation": "references/tomato_SLM_r2.1/SLM_r2.1_genomic.gtf",
    "annotationFormat": "gtf"
  }
};
