#!/usr/bin/env bash
#
# Scans references/*/ subdirectories and generates manifest.js
# Usage: cd references && ./update_manifest.sh
#        OR: ./references/update_manifest.sh (from project root)

set -euo pipefail

# Resolve script directory so it works from any working directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MANIFEST="$SCRIPT_DIR/manifest.js"

echo "// Auto-generated by update_manifest.sh — do not edit manually" > "$MANIFEST"
echo "var CUSTOM_GENOMES = {" >> "$MANIFEST"

first=true
for dir in "$SCRIPT_DIR"/*/; do
    [ -d "$dir" ] || continue
    dirname="$(basename "$dir")"

    # Find FASTA file (supports .fa, .fasta, .fna and gzipped variants)
    fasta=""
    for ext in fa fasta fna fa.gz fasta.gz fna.gz; do
        match=$(find "$dir" -maxdepth 1 -name "*.$ext" -print -quit 2>/dev/null)
        if [ -n "$match" ]; then
            fasta="$(basename "$match")"
            break
        fi
    done

    if [ -z "$fasta" ]; then
        echo "WARNING: No FASTA file found in $dirname/, skipping" >&2
        continue
    fi

    # Check for FASTA index (.fai or .gzi for compressed)
    index="null"
    if [ -f "$dir/${fasta}.fai" ]; then
        index="\"references/${dirname}/${fasta}.fai\""
    elif [ -f "$dir/${fasta}.gzi" ]; then
        index="\"references/${dirname}/${fasta}.gzi\""
    fi

    # Find annotation file (GTF or GFF, including gzipped)
    annotation="null"
    annotation_format="null"
    for ext in gtf gff gff3 gtf.gz gff.gz gff3.gz; do
        match=$(find "$dir" -maxdepth 1 -name "*.$ext" -print -quit 2>/dev/null)
        if [ -n "$match" ]; then
            annotation="\"references/${dirname}/$(basename "$match")\""
            if echo "$ext" | grep -q "^gtf"; then
                annotation_format="\"gtf\""
            else
                annotation_format="\"gff3\""
            fi
            break
        fi
    done

    # Emit JSON entry
    if [ "$first" = true ]; then
        first=false
    else
        echo "," >> "$MANIFEST"
    fi

    printf '  "%s": {\n' "$dirname" >> "$MANIFEST"
    printf '    "label": "%s",\n' "$dirname" >> "$MANIFEST"
    printf '    "fasta": "references/%s/%s",\n' "$dirname" "$fasta" >> "$MANIFEST"
    printf '    "index": %s,\n' "$index" >> "$MANIFEST"
    printf '    "annotation": %s,\n' "$annotation" >> "$MANIFEST"
    printf '    "annotationFormat": %s\n' "$annotation_format" >> "$MANIFEST"
    printf '  }' >> "$MANIFEST"

    echo "  Added: $dirname (fasta=$fasta, index=${index}, annotation=${annotation})" >&2
done

echo "" >> "$MANIFEST"
echo "};" >> "$MANIFEST"

echo "Manifest written to $MANIFEST" >&2
